# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_system_ila_0_0/evo_v1_system_ila_0_0.xci
# IP: The module: 'evo_v1_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_system_ila_0_0/bd_0/bd_aef2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_aef2 || ORIG_REF_NAME==bd_aef2}]

# IP: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_system_ila_0_0/bd_0/ip/ip_0/bd_aef2_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_aef2_ila_lib_0 || ORIG_REF_NAME==bd_aef2_ila_lib_0}]

# XDC: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_aef2_ila_lib_0 || ORIG_REF_NAME==bd_aef2_ila_lib_0}] {/U0 }]/U0 ]]

# XDC: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_system_ila_0_0/bd_0/ip/ip_0/bd_aef2_ila_lib_0_ooc.xdc

# XDC: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_system_ila_0_0/bd_0/bd_aef2_ooc.xdc

# IP: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_system_ila_0_0/evo_v1_system_ila_0_0.xci
# IP: The module: 'evo_v1_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_system_ila_0_0/bd_0/bd_aef2.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_aef2 || ORIG_REF_NAME==bd_aef2}]

# IP: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_system_ila_0_0/bd_0/ip/ip_0/bd_aef2_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_aef2_ila_lib_0 || ORIG_REF_NAME==bd_aef2_ila_lib_0}]

# XDC: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_aef2_ila_lib_0 || ORIG_REF_NAME==bd_aef2_ila_lib_0}] {/U0 }]/U0 ]]

# XDC: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_system_ila_0_0/bd_0/ip/ip_0/bd_aef2_ila_lib_0_ooc.xdc

# XDC: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_system_ila_0_0/bd_0/bd_aef2_ooc.xdc
