# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_axi_gpio_0_0_2/evo_v1_axi_gpio_0_0.xci
# IP: The module: 'evo_v1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_axi_gpio_0_0_2/evo_v1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'evo_v1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_axi_gpio_0_0_2/evo_v1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'evo_v1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_axi_gpio_0_0_2/evo_v1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'evo_v1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_axi_gpio_0_0_2/evo_v1_axi_gpio_0_0.xci
# IP: The module: 'evo_v1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_axi_gpio_0_0_2/evo_v1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'evo_v1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_axi_gpio_0_0_2/evo_v1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'evo_v1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projet/Vivado/Evo/Evo.srcs/sources_1/bd/evo_v1/ip/evo_v1_axi_gpio_0_0_2/evo_v1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'evo_v1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
