# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/evo_v1/evo_v1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==evo_v1 || ORIG_REF_NAME==evo_v1}]

# IP: bd/evo_v1/ip/evo_v1_processing_system7_0_0/evo_v1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==evo_v1_processing_system7_0_0 || ORIG_REF_NAME==evo_v1_processing_system7_0_0}]

# IP: bd/evo_v1/ip/evo_v1_axi_gpio_0_0/evo_v1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==evo_v1_axi_gpio_0_0 || ORIG_REF_NAME==evo_v1_axi_gpio_0_0}]

# IP: bd/evo_v1/ip/evo_v1_axi_gpio_1_0/evo_v1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==evo_v1_axi_gpio_1_0 || ORIG_REF_NAME==evo_v1_axi_gpio_1_0}]

# IP: bd/evo_v1/ip/evo_v1_ps7_0_axi_periph_0/evo_v1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==evo_v1_ps7_0_axi_periph_0 || ORIG_REF_NAME==evo_v1_ps7_0_axi_periph_0}]

# IP: bd/evo_v1/ip/evo_v1_rst_ps7_0_100M_0/evo_v1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==evo_v1_rst_ps7_0_100M_0 || ORIG_REF_NAME==evo_v1_rst_ps7_0_100M_0}]

# IP: bd/evo_v1/ip/evo_v1_xbar_0/evo_v1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==evo_v1_xbar_0 || ORIG_REF_NAME==evo_v1_xbar_0}]

# IP: bd/evo_v1/ip/evo_v1_auto_pc_0/evo_v1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==evo_v1_auto_pc_0 || ORIG_REF_NAME==evo_v1_auto_pc_0}]

# XDC: bd/evo_v1/evo_v1_ooc.xdc
